---
name: Mochad Daemon
version: dev
slug: mochad-daemon
description: Mochad Daemon add-on by Community Home Assistant Add-ons
url: https://github.com/Nathanlclark/ha-addon-mochad
init: false
arch:
#  - aarch64
  - amd64
#  - armhf
#  - armv7
#  - i386
options:
  log_level: info
  device_bus_path: /dev/bus/usb/002
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  device_bus_path: int(1,120)
